version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/orangeexchange
      SPRING_DATASOURCE_USERNAME: orange
      SPRING_DATASOURCE_PASSWORD: 123456

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
      POSTGRES_INITDB_ARGS: "-c 'create database orangeexchange;' -c 'create user orange with password '\''123456'\''; grant all privileges on database orangeexchange to orange;'"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: